[package]
name = "rle_morph"
version = "0.1.0"
authors = ["Luka Tadić <luka.tadic@fer.hr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
png = "0.16.1"
